### ISSUE TITLE
Out of memory on huge load

### ISSUE THREAD

**Issue by VincentGuinaudeau** [chad3814/es6-native-map#8]
hello,

I use this module for what you say it's does : workaround the V8 memory limit. But when i use it for some huge caching, i end up with a out of memory, desipite i have several Go left on RAM.

So i start looking thinking it was a bug from my project, but it seem your modules don't completely free V8 memory.

To test this, you can run your stressor test (without forcing gc) with the --trace-gc option. Then you see, cycle by cycle, the memory space of v8 slowly increase (i use to store very long string on your map, and the difference between global nodeJs memory and V8 internal memory is lesser here).

It will awesome if you can solve this issues because your two module (hashtable and es6-native-map) are the only two who can't expend v8 memory as far as i kwon.

**Comment by chad3814** [comment]
I think I fixed this in 3.1.0 today

**Comment by VincentGuinaudeau** [comment]
Sorry to say it, but no this problem stil exist.

Here is a slightly modified version of your map_stressor.js, who don't clear the table and monitor v8 heap size :

``` javascript
'use strict';

var NodeMap = require('./');
var v8 = require("v8")

var generateId = function (len) {
    var first_chars = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'];
    var chars = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1', '2', '3', '4', '5', '6', '7', \
'8', '9'];
    var id = '';
    id += first_chars[Math.floor(Math.random() * first_chars.length)];
    len -= 1;
    var i;
    for (i = 0; i < len; i += 1) {
        id += chars[Math.floor(Math.random() * chars.length)];
    }
    return id;
};

var map = new NodeMap();
var count = 0;
var stat;

var runCycle = function () {
    var i;
    for (i = 0; i < 100000; i++) {
        map.set(generateId(10), generateId(20));
    }
    count++;
    stat = v8.getHeapStatistics();
    console.log('iteration', count * 10000, (stat.total_heap_size * 100) / stat.heap_size_limit, '%');
    process.nextTick(runCycle);
};

runCycle();
```

This also work by loading a file of several Go into your map.

**Comment by chad3814** [comment]
I mean, you are continuously adding strings into your map. If you don't clear it, it's going to get bigger because you are storing more and more data.

**Comment by VincentGuinaudeau** [comment]
Sure, but I have test this code on a 16 Go server, and that’s v8 who give up despite it still room on the memory.

So this still an issues for me, because this module claim to create a hashtable outside of v8 memory, but the is this is not completely the case.

Now if you say this module have to work this way it’s okay for me. But please change your readme to avoid confusion, because when you say “native hashmap data structure that exists outside of V8's memory constraints”, other like me will expect a hashtable who can store as much data has they want.
